version: '3.8'

services:
  # Servicio de Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/EducaFinanciera
    networks:
      - app-network

  # Servicio de Frontend
  frontend:
    build:
      context: ./FrontEducaFinanciera
      dockerfile: Dockerfile
    networks:
      - app-network

  # Servicio Primario de MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Servicio de Respaldo de MongoDB
  mongodb-backup:
    image: mongo:latest
    container_name: mongodb-backup
    ports:
      - "27018:27017"
    volumes:
      - mongo-backup-data:/data/db
    networks:
      - app-network

  # Servicio de Nginx
  nginx:
    build:
      context: ./FrontEducaFinanciera
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"  # Para HTTPS
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-backup-data:
