version: '3.8'

services:
  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./backend:/user/src/app  
    - /user/src/app/node_modules  
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/EducaFinanciera
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./FrontEducaFinanciera
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  # Primary MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Backup MongoDB service
  mongodb-backup:
    image: mongo:latest
    container_name: mongodb-backup
    ports:
      - "27018:27017"
    volumes:
      - mongo-backup-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-backup-data: